### PR TITLE
Updating the types and docstrings for all these functions.

### PR DESCRIPTION
**Pull request by MalcolmSlaney**

### CODE REVIEW

**Review by fotisdr — COMMENTED** [review]
Hi Malcolm,

I've made some minor changes throughout the code, and also added some comments that will hopefully give you a better idea for the functionality of the unslice function. I'm still not certain whether the ignore_first_set parameter would do exactly what it was intended to do as I haven't fully tested it (and didn't write this in the first place), so I think it is safe to ignore this part of the function for now and just use it with these parameters set to 0 (and manually crop any context beforehands). Let me know if you have any additional changes to make or any questions, otherwise I'll make sure I merge these changes with our current version of the repository.

Thanks!
Fotis

**Comment by MalcolmSlaney** [comment]
Ping.

Are you still planning to merge these changes?  I hope the code is more understandable now, and I hope others can benefit.

- Malcolm

**Comment by fotisdr** [comment]
Hi Malcolm,

I was waiting for a reply to make sure that you've also finished with the revision of the codes. I'll go ahead and merge these changes soon. Thank you very much for your documentation, all this definitely makes the code much more understandable now.

**Comment by MalcolmSlaney** [comment]
Cool… nice to see this is official now.

I am afraid I am not nearly as facile with GitHub as I like, so I’ll get some help on Saturday to merge the official stuff back into my branch (or abandon mine.)

You never answered my question about whether the ensuing DNN hearing aid models are available.  I hope that wasn’t an uncomfortable question.  I’d love to run some tests on it, mostly around dynamic range issues and testing how well it matches/predicts the NAL prescriptions. Is that possible?  Under and NDA or other license?

Good to work with you, and I’d love to do more.

- Malcolm

**Comment by fotisdr** [comment]
Sorry I completely missed your question, I don't remember reading anything along those lines so it was definitely not intentional. 

We only have one DNN hearing-aid model available at the moment, which was presented in last year's ICASSP. You can find the github repository here and test it out as much as you want, it is under the UGent academic license that we always use: https://github.com/fotisdr/DNN-HA. 

As you'll read in the repository, this DNN-HA model was developed to accommodate different individualised solutions for OHC loss  based on a provided audiogram input (alongside the sound input). You can read more about this in our ICASSP 2023 paper: https://ieeexplore.ieee.org/abstract/document/10094887

On the other hand, the individualised DNN-HA models we built as part of our previous paper (compensation for cochlear synaptopathy, OHC loss and combinations of both) have not been made available. So if you want to test these out it is probably best to directly contact Sarah and see whether it is possible.

Thanks again for all your help, happy to collaborate on this!

Fotis

**Pull request merged**
